### ISSUE TITLE
data.R

### ISSUE THREAD

**Issue by yuw444** [TearsWillFall/ULPwgs#1]
Sorry to bother you here. 

This is not necessarily an issue, I came across your `data.R`, and found my flowcell pattern doesn't match any of them. 

FYI, the pattern in my fastq file is `NB501139:187:H2Y5LBGXB`. Could you point me in some direction to find out the sequencer and flowcell info according to this? 

I really appreciate any help you can provide.

**Comment by TearsWillFall** [comment]
My flowcell/instrument pattern list is based on the 10XGenome implementation done here: https://github.com/10XGenomics/supernova/blob/master/tenkit/lib/python/tenkit/illumina_instrument.py

The only way of knowing both the instrument/flowcell with certainty is if you do the sequencing yourself. I'm saying this because there isn't a publicly available and complete database of matching IDs to flowcells/instruments. What you see here is what others have collected over time trying to figure out the same as you.


Instrument ID : NB501139

The sequencing instrument most likely is NextSeq (550?) as the instrument ID starts with NB000000. 

-------------------------------------------------------------------------------

Flowcell ID : H2Y5LBGXB

Similarly, the flowcell ID seems to indicate that the closest matches in the NextSeq patterns list are:


"H[A-Z,0-9]{4}BGXX$"
"H[A-Z,0-9]{4}BGXY$"
"H[A-Z,0-9]{4}BGX2$"

All of these correspond to NextSeq High Output Flow Cells.

"H[A-Z,0-9]{4}AFXX$"

Whereas this pattern would correspond to a NextSeq Med Output Flow Cells.

 
Because your flowcell id differs in the last letter its most likely to be a NextSeq High Output Flow too.


If you really want to be 100% sure about these you should try to contact Illumina and ask them.

**Comment by yuw444** [comment]
Thanks for your prompt and detailed explanations.
